name: Ejecutar Pruebas Automáticas

on:
  push:
    branches:
      - test
    paths:
      - "__tests__/**"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clonar el repositorio
        uses: actions/checkout@v4

      - name: 📦 Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: 📂 Instalar dependencias
        run: npm ci

      - name: 📂 Crear directorio de reportes
        run: mkdir -p reports

      - name: 🚀 Ejecutar pruebas con Jest
        run: npx jest --ci --reporters=default --reporters=jest-html-reporter

      - name: 📄 Guardar reporte de pruebas
        uses: actions/upload-artifact@v4
        with:
          name: jest-test-report
          path: reports/jest-report.html
          retention-days: 7
